// *** EET-specific initializations ***

ACTION_IF (GAME_IS ~eet~) BEGIN
  OUTER_SET bg2_chapter = 12
  OUTER_SPRINT bg1_area_prefix ~BG~
END ELSE BEGIN
  OUTER_SET bg2_chapter = 0
  OUTER_SPRINT bg1_area_prefix ~AR~
END

// Setting bg2_chapter_1, bg2_chapter_2, ... to actual chapter value for BG2 part of the game
OUTER_FOR (i = 1; i < 11; ++i) BEGIN
  OUTER_SET bg2_chapter += 1
  OUTER_TEXT_SPRINT name_source ~bg2_chapter_%i%~
  OUTER_SET EVAL ~%name_source%~ = bg2_chapter
END
